import { Peer } from 'https://cdn.jsdelivr.net/npm/peerjs@1.5.4/+esm';

const app=document.querySelector('#app');
const state={peer:null,conn:null,isHost:false,room:'',name:'',game:null};
const chars=[
 {name:'Dracula',icon:'♛',type:'undead',clue:'เชื้อสายผู้ดี'}, {name:'Mina',icon:'☽',type:'human',clue:'สวมผ้าคลุม'},
 {name:'หมาป่า',icon:'♞',type:'beast',clue:'ชอบคืนพระจันทร์เต็มดวง'}, {name:'มัมมี่',icon:'☥',type:'undead',clue:'พันด้วยผ้าลินิน'},
 {name:'แม่มด',icon:'✦',type:'magic',clue:'พกยาวิเศษ'}, {name:'สัตว์ประหลาด',icon:'⚡',type:'created',clue:'มีรอยเย็บ'},
 {name:'ผี',icon:'♢',type:'undead',clue:'ไร้เงาสะท้อน'}, {name:'การ์กอยล์',icon:'♜',type:'beast',clue:'ปีกหิน'}];
const questions=[['undead','คุณเป็นผู้ไม่ตายใช่ไหม?'],['human','คุณเป็นมนุษย์ใช่ไหม?'],['beast','คุณเป็นอสูรร้ายใช่ไหม?'],['magic','คุณใช้เวทมนตร์ใช่ไหม?'],['created','คุณถูกสร้างขึ้นมาใช่ไหม?']];
const letters='ABCDEFGHJKLMNPQRSTUVWXYZ23456789', code=()=>Array.from({length:5},()=>letters[Math.random()*letters.length|0]).join('');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const send=m=>state.conn?.open&&state.conn.send(m), mine=()=>state.game?.players.find(p=>p.id===state.peer?.id);

function home(note='เชิญเพื่อนด้วยรหัสห้อง แล้วเริ่มงานเลี้ยงได้เลย') { app.innerHTML=`<section class="hero"><div class="moon"></div><div class="crest">♛</div><p class="eyebrow">A DEDUCTION CARD GAME</p><h1>Dracula’s<br><em>Feast</em></h1><p class="subtitle">New Blood · 4–8 คน · 10–15 นาที</p><div class="panel lobby"><label>ชื่อของคุณ<input id="name" maxlength="18" placeholder="เช่น Mina" value="${esc(state.name)}"></label><div class="choices"><button class="primary" id="host">สร้างห้องใหม่ <span>→</span></button><span>หรือ</span><div class="join"><input id="room" maxlength="5" placeholder="รหัสห้อง"><button id="join">เข้าร่วม</button></div></div><p class="notice">${note}</p></div><div class="how"><div><b>01</b><span>ถามแขก</span></div><div><b>02</b><span>ชวนเต้นรำ</span></div><div><b>03</b><span>กล่าวหาให้ถูกต้อง</span></div></div></section><footer>เกมแฟนเมดสำหรับเล่นส่วนตัว · ไม่ใช่ผลิตภัณฑ์ทางการ</footer>`;document.querySelector('#host').onclick=host;document.querySelector('#join').onclick=join; }
function nameOK(){state.name=document.querySelector('#name').value.trim();if(!state.name){document.querySelector('.notice').textContent='โปรดใส่ชื่อก่อนเริ่ม';return false}return true}
function host(){if(!nameOK())return;state.isHost=true;state.room=code();state.peer=new Peer('draculas-feast-'+state.room);state.peer.on('open',()=>{state.game={phase:'lobby',players:[{id:state.peer.id,name:state.name}],turn:0,log:[],dances:[],pending:null};lobby()});state.peer.on('connection',connectHost);state.peer.on('error',()=>home('สร้างห้องไม่สำเร็จ ลองใหม่อีกครั้ง'))}
function join(){if(!nameOK())return;const r=document.querySelector('#room').value.toUpperCase().trim();if(r.length!==5){document.querySelector('.notice').textContent='รหัสห้องมี 5 ตัวอักษร';return}state.room=r;state.peer=new Peer();state.peer.on('open',()=>{state.conn=state.peer.connect('draculas-feast-'+r,{reliable:true});state.conn.on('open',()=>send({t:'join',id:state.peer.id,name:state.name}));state.conn.on('data',clientMsg);});state.peer.on('error',()=>home('ไม่พบห้องนี้ หรือเจ้าของห้องปิดไปแล้ว'))}
function connectHost(c){c.on('data',m=>{if(m.t==='join'){if(state.game.phase!=='lobby'||state.game.players.length===8)return c.send({t:'error',m:'ห้องเริ่มแล้วหรือเต็มแล้ว'});state.game.players.push({id:m.id,name:m.name});sync();lobby()}else hostMsg(m)});c.on('close',()=>{if(state.game?.phase==='lobby'){state.game.players=state.game.players.filter(p=>p.id!==c.peer);sync();lobby()}})}
function clientMsg(m){if(m.t==='state'){state.game=m.g;render()}if(m.t==='error')home(m.m)}
function project(id){const g=structuredClone(state.game);g.players.forEach(p=>{if(p.id!==id&&!g.dances.some(d=>d.includes(id)&&d.includes(p.id)))delete p.character});return g}
function sync(){Object.values(state.peer.connections||{}).flat().forEach(c=>c.open&&c.send({t:'state',g:project(c.peer)}))}
function player(p,action=false){const c=p.character;return `<article class="player ${action?'actionable':''}" data-id="${p.id}"><div class="avatar">${p.name[0]?.toUpperCase()}</div><div><strong>${esc(p.name)}</strong><small>${c?`${c.icon} ${c.name}`:'ตัวตนยังเป็นความลับ'}</small></div>${action?'<span class="target">เลือก</span>':''}</article>`}
function lobby(){const p=state.game.players;app.innerHTML=`<section class="room"><header><div class="brand">♛ <span>DRACULA’S FEAST</span></div><div class="status"><i></i> ห้องเปิดอยู่</div></header><div class="room-code"><span>รหัสห้องของคุณ</span><strong>${state.room}</strong><button id="copy">คัดลอกรหัส</button></div><div class="lobby-content"><p class="eyebrow">WAITING FOR THE GUESTS</p><h2>ผู้ร่วมงาน <em>${p.length}/8</em></h2><div class="player-grid">${p.map(x=>player(x)).join('')}</div>${state.isHost?`<button id="start" class="primary large" ${p.length<4?'disabled':''}>เริ่มงานเลี้ยง <span>→</span></button><p class="hint">ต้องมี 4–8 คนจึงจะเริ่มได้</p>`:'<div class="waiting">กำลังรอเจ้าของห้องเริ่มเกม…</div>'}</div></section>`;document.querySelector('#copy').onclick=()=>navigator.clipboard.writeText(state.room).then(()=>document.querySelector('#copy').textContent='คัดลอกแล้ว ✓');document.querySelector('#start')?.onclick=start}
function start(){state.game.players.sort(()=>Math.random()-.5).forEach((p,i)=>p.character=chars[i]);Object.assign(state.game,{phase:'play',turn:0,log:['แขกทุกคนได้รับบัตรตัวตนลับแล้ว','ถึงเวลาสังเกต ตั้งคำถาม และหาความจริง']});sync();game()}
function render(){state.game.phase==='lobby'?lobby():game()}
const typeName=t=>({undead:'ผู้ไม่ตาย',human:'มนุษย์',beast:'อสูร',magic:'ผู้ใช้เวท',created:'สิ่งที่ถูกสร้าง'}[t]);
function game(){const g=state.isHost?project(state.peer.id):state.game,me=g.players.find(p=>p.id===state.peer.id),active=g.players[g.turn],myTurn=active.id===me.id,offer=g.pending?.kind==='dance'&&g.pending.target===me.id;let content='';if(g.phase==='end')content=`<div class="result"><div>♛</div><h3>${g.winner.name} ชนะงานเลี้ยง!</h3><p>กล่าวหา ${g.accused.name} ได้ถูกต้องว่าเป็น ${g.accused.character.name}</p>${state.isHost?'<button class="primary" id="restart">เล่นอีกครั้ง</button>':''}</div>`;else if(offer)content=`<div class="reveal-card"><div>♫</div><h3>${g.pending.fromName} ชวนคุณเต้นรำ</h3><p>หากตอบตกลง ทั้งสองฝ่ายจะเห็นตัวตนของกันและกันตลอดเกม</p><button class="primary" id="accept">ตกลงเต้นรำ</button><button class="outline" id="decline">ปฏิเสธ</button></div>`;else if(myTurn)content=menu(g,me);else content=`<div class="instruction">กำลังรอ <b>${esc(active.name)}</b> เลือกการกระทำ…</div><div class="player-grid table-grid">${g.players.map(x=>player(x)).join('')}</div>`;app.innerHTML=`<section class="game"><header><div class="brand">♛ <span>DRACULA’S FEAST</span></div><div class="round">✦ ตาของ ${esc(active.name)}</div><div class="room-tag">ห้อง ${state.room}</div></header><div class="game-main"><aside><p class="eyebrow">YOUR IDENTITY</p><div class="role-card"><div class="role-icon">${me.character?.icon||'?'}</div><h3>${me.character?.name||'กำลังแจกบัตร…'}</h3><p>${me.character?`${me.character.clue} · ${typeName(me.character.type)}`:''}</p></div><div class="chronicle"><b>บันทึกงานเลี้ยง</b>${g.log.slice(-5).reverse().map(x=>'<p>'+esc(x)+'</p>').join('')}</div></aside><section class="table"><p class="eyebrow">FIND THE MONSTERS</p><h2>${g.phase==='end'?'คำตอบปรากฏแล้ว':'ใครกันแน่ที่อยู่ตรงหน้า?'}</h2>${content}</section></div></section>`;document.querySelectorAll('.actionable').forEach(x=>x.onclick=()=>target(x.dataset.id));document.querySelector('#accept')?.onclick=()=>send({t:'reply',yes:true});document.querySelector('#decline')?.onclick=()=>send({t:'reply',yes:false});document.querySelector('#restart')?.onclick=restart}
function menu(g,me){if(g.pending?.from===me.id)return `<div class="instruction">กำลังรอคำตอบจาก ${esc(g.pending.targetName)}…</div>`;if(g.pending?.kind&&!g.pending.target)return `<div class="instruction">เลือกแขกที่คุณต้องการ${g.pending.kind==='inquire'?'ถาม':g.pending.kind==='dance'?'ชวนเต้นรำ':'กล่าวหา'}</div><div class="player-grid table-grid">${g.players.map(p=>player(p,p.id!==me.id)).join('')}</div>`;if(g.pending?.kind==='inquire')return `<div class="instruction">เลือกคำถามเพื่อถาม ${esc(g.pending.targetName)}</div><div class="question-list">${questions.map(([t,q])=>`<button class="outline ask" data-type="${t}">${q}</button>`).join('')}</div>`;if(g.pending?.kind==='accuse')return `<div class="instruction">คุณกำลังกล่าวหา ${esc(g.pending.targetName)} ว่าเป็นใคร?</div><div class="question-list">${chars.slice(0,g.players.length).map(c=>`<button class="outline accuse" data-char="${c.name}">${c.icon} ${c.name}</button>`).join('')}</div>`;return `<div class="action-menu"><button class="primary action-btn" data-action="inquire"><b>?</b><span>ถามแขก<small>รับคำตอบ YES หรือ NO ที่เป็นจริง</small></span></button><button class="outline action-btn" data-action="dance"><b>♫</b><span>ชวนเต้นรำ<small>ทั้งคู่จะเปิดบัตรตัวตนต่อกัน</small></span></button><button class="outline action-btn" data-action="accuse"><b>!</b><span>กล่าวหา<small>ทายตัวตนของแขกคนหนึ่ง</small></span></button></div>`}
function target(id){const g=state.game,me=mine();if(g.players[g.turn].id!==me.id||id===me.id)return;const p=g.players.find(x=>x.id===id);if(g.pending?.kind){sendAction({t:'target',kind:g.pending.kind,target:id,targetName:p.name});return} }
document.addEventListener('click',e=>{const g=state.game,me=mine();if(!g||g.phase!=='play'||g.players[g.turn]?.id!==me.id)return;const a=e.target.closest('[data-action]')?.dataset.action;if(a){g.pending={kind:a};render()}if(e.target.matches('.ask'))sendAction({t:'inquire',target:g.pending.target,type:e.target.dataset.type});if(e.target.matches('.accuse'))sendAction({t:'accuse',target:g.pending.target,char:e.target.dataset.char})});
function sendAction(m){state.isHost?hostMsg(m):send(m)}
function hostMsg(m){const g=state.game,actor=g.players[g.turn];if(m.t==='target'){g.pending={kind:m.kind,target:m.target,targetName:m.targetName,from:actor.id,fromName:actor.name};sync();game();return}if(m.t==='inquire'){const p=g.players.find(x=>x.id===m.target),yes=p.character.type===m.type;g.log.push(`${actor.name} ถาม ${p.name}: “${questions.find(q=>q[0]===m.type)[1]}” — ${yes?'YES':'NO'}`);next();return}if(m.t==='reply'){const p=g.players.find(x=>x.id===g.pending.target);if(m.yes){g.dances.push([g.pending.from,p.id]);g.log.push(`${actor.name} และ ${p.name} เต้นรำด้วยกัน และแลกเปลี่ยนตัวตน`)}else g.log.push(`${p.name} ปฏิเสธคำชวนเต้นรำของ ${actor.name}`);next();return}if(m.t==='accuse'){const p=g.players.find(x=>x.id===m.target),correct=p.character.name===m.char;g.log.push(`${actor.name} กล่าวหาว่า ${p.name} คือ ${m.char} — ${correct?'ถูกต้อง!':'ยังไม่ถูกต้อง'}`);if(correct){Object.assign(g,{phase:'end',winner:actor,accused:p,pending:null});sync();game()}else next()}}
function next(){state.game.pending=null;state.game.turn=(state.game.turn+1)%state.game.players.length;sync();game()}
function restart(){state.game.phase='lobby';state.game.players.forEach(p=>delete p.character);state.game.dances=[];state.game.log=[];state.game.pending=null;sync();lobby()}
home();
